
[env]
TERM = "xterm-256color"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[window]
opacity = 0.97
title = "Alacritty"
startup_mode = "SimpleFullscreen"
option_as_alt = "Both"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 8
y = 8

[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml",
    "~/.config/alacritty/machine-specific.toml",
]
