#!/bin/bash

##### SSH Agent

SSH_PID_FILE="$HOME/.config/ssh-agent.pid"
SSH_AUTH_SOCK="$HOME/.config/ssh-agent.sock"
if [ -z "$SSH_AGENT_PID" ]
then
   # no PID exported, try to get it from pidfile
   SSH_AGENT_PID=$(cat "$SSH_PID_FILE")
fi

if ! kill -0 $SSH_AGENT_PID &> /dev/null
then
   # the agent is not running, start it
   rm "$SSH_AUTH_SOCK" &> /dev/null
   eval "$(ssh-agent -s -a "$SSH_AUTH_SOCK")" >/dev/null 2>&1 || echo "Warning: failed to start SSH agent"
   echo "$SSH_AGENT_PID" > "$SSH_PID_FILE"
fi

export SSH_AGENT_PID
export SSH_AUTH_SOCK
