#!/bin/bash

open_bracket="%F{#4e535c}[%f"
close_bracket="%F{#4e535c}]%f"
username="%F{magenta}%B%n%b%f"
working_dir="%F{yellow}%B%1~%b%f"
prompt_char="%F{green}%(#.#.$)%f"

PROMPT="${open_bracket}${username}${close_bracket}${open_bracket}${working_dir}${close_bracket}${prompt_char} "
